### ISSUE TITLE
Có một cái Network trong `hyperledger/fabric-samples/test-network`

### ISSUE THREAD

**Issue by NguyenAnhTuan1912** [phapdev/NFT-Marketplace#16]
# Có một cái Network trong `hyperledger/fabric-samples/test-network`
## Mục tiêu của bài viết
Trong bài viết này t sẽ tọc vạch cái folder `hyperledger/fabric-samples/test-network`, với một số mục đích như là:
- Tìm hiểu xem để start up một network thì mình có những thông tin gì: như là thông tin của tổ chức, thông tin của docker, ...
- Cấu trúc của các thông tin đó
- Từ đó mà mình có thể custom lại cho chính project của mình

### Cấu trúc thư mục `hyperledger/fabric-samples/test-network`
Cấu trúc thư mục được biểu diễn dưới dạng là một cây thư mục như sau:
```
.
├── addOrg3
├── configtx
├── docker
├── organizations
├── scripts
├── system-genesis-block
├── .gitignore
├── network.sh
└── README.md
```

Dự đoán:
- __addOrg3__ là folder dùng để thêm một tổ chức mới vào trong NET, như tụi m đã biết thì để thêm một tổ chức mới (Peer mới) thì buộc phải có đầy đủ thông tin của tổ chức đó.
- __configtx__ là file dùng để cài đặt các thông tin của peers, đầu tiên là có 2 peers là Org1 và Org2. Trong bài của mình thì mình chỉ cần 1 peer thôi.
- __docker__ là folder chứa các file xml để khởi tạo ra các server cần thiết trong NET. Hiện tại thì mình có thể thấy có 3 file thì sẽ bao gồm 3 server, đúng hơn là 3 Docker Container. CA, CouchDB và NET, quá đơn giản.
- __organizations__ là folder chứa các thông tin để config cho các orginazation, mình sẽ tìm hiểu sau.
- __scripts__ là folder chứa các script được Hyperledger cài đặt sẵn.
- __system-genesis-block__ không rõ lắm

### Nội dung của các folder bên trong
Ở trên thì t chỉ mới dự đoán thôi, giờ là tọc vạch bên trong xem từng nội dung của nó có gì, thứ tự sẽ như sau:
`docker --> configtx --> organizations`

#### docker
Vì __NET__, __DB__ và __CA Server__ đều được deploy bằng Docker (local), nên mình phải config các thông tin cho 3 đối tượng này. Đầu tiên là CA Server (không đầy đủ, chỉ cần của org1 là được, còn của org2 thì tụi m tự vào xem), lưu ý là các thông tin bên trong t sẽ comment ở trong đó luôn
```yaml
version: '2'

networks:
  test:
    name: fabric_test

services:

  # Tên của service
  ca_org1:
    # Image, được build sẵn bởi Hyperledger
    image: hyperledger/fabric-ca:latest
    # Các biến môi trường
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    # PORT được dùng để host
    ports:
      - "7054:7054"
      - "17054:17054"
    # Lệnh để khởi tạo
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    # Đường dẫn mà source gốc của ứng dụng, program tồn tại (***)
    volumes:
      - ../organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    container_name: ca_org1
    networks:
      - test
```
Một số lưu ý:
- Trong file này thì mình sẽ config để deploy 2 server CA cho Org1 và Org2. Vì thế nên mình mới dùng docker-compose thay vì là docker bình thường.
- Các biến môi trường sẽ được sử dụng trong việc start up CA Server.
- Tại thời điểm chưa UP NET thì trong đường dẫn `organizations/fabric-ca/org1:` không hề thấy folder nào là `etc` dựa trên thuộc tính `volumes`. Có thể là nó sẽ được thêm trong quá trình UP NET hay làm sao đó.

Tiếp theo là __DB__ (CouchDB)
```yaml
version: '2'

networks:
  test:
    name: fabric_test

services:
  couchdb0:
    container_name: couchdb0
    image: couchdb:3.1.1
    # Tạo 2 biến COUCHDB_USER and COUCHDB_PASSWORD để thêm user và password cho CouchDB
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - test

  peer0.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME và CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # là hai biến mà mà nó cấp cho credentials cho ledger có thể kết nối tới DB. 2 biến này
      # buộc phải giống với COUCHDB_USER và COUCHDB_PASSWORD ở trên
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0

  # Tương tự như couchdb0
  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    networks:
      - test

  peer0.org2.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb1
```
Một số lưu ý:
- Tụi m có thể thấy là có tới 2 DB được deploy.
- DB sẽ được deploy trước NET, dựa vào thuộc tính `depends_on` trên file, tại sao t biết thì đọc tiếp nhé.

Cuối cùng là NET, trong file này cũng có rất nhiều thông tin khác, nhưng t sẽ chỉ tập chung vào các thông tin để deploy NET
```yaml
peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      # FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      # Id của PEER
      - CORE_PEER_ID=peer0.org1.example.com
      # Địa chỉ của PEER
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      # Địa chỉ của Chaincode của PEER
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17051
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 17051:17051
    networks:
      - test

```
Một số lưu ý:
- Tới đây thì thông tin để host một NET thì có rất nhiều và cũng hơi khó hiểu.
- Đọc thêm trong phần Tham khảo [4] để hiểu thêm.
- Trong file này còn có một service nữa là `orderer.example.com`, nó là một service mà đảm bảo các peer sẽ chỉ tập chung vào việc validate các giao dịch và commit các giao dịch vào sổ cái. Còn việc thêm block theo thứ tự nào thì dịch vụ này nó sẽ lo việc đó.

#### configtx
Trong thư mục này chứa một file cùng tên là `configtx.yaml`, trong file này chứa một số định nghĩa được chia ra thành nhiều phần:
1. __Organization's Identity__, các identities này được Hyperledger dùng để config sau.
2. __Capabilities__, nó định nghĩa các tính năng mà phải được tồn tại trong Fabric Binary (các file exe, sh, ...) để cho Binary đó có thể dùng ổn định trong NET
3. Các sections dưới không hiểu lắm nên không viết nữa :v Đại loại là nó là các values được encode để dùng config cho các giao dịch trong hoặc trong các tham số có liên quan của ứng dụng.

#### organizations
Theo t hiểu thì folder này nó sẽ chứa các thông tin liên quan tới các organizations. Trong này có một file binary `ccp-generate.sh` để tạo ra một Connection Profile, và tụi m có thể thấy là bên trong có Template của Connection Profile ở hai dạng là JSON và YAML.

File binary `ccp-generate.sh` này dùng để tạo ra một connection profile, connection profile này được dùng trong các đoạn script mà bữa ae mình làm:

```ts
let connectionProfile = JSON.parse(fs.readFileSync(
  path.join(
    testNetworkRoot,
    'organizations/peerOrganizations',
    orgName,
    `/connection-${orgNameWithoutDomain}.json`),
    'utf8'
  )
);
```
Vậy 2 folders `cryptogen` và `fabric-ca` để làm gì? Có một số điều:
- Khi chạy lệnh `./network.sh` thì nó sẽ tạo certificates và keys cho 2 peers (org1 và org2), thì nó sẽ sử dụng các file config trong `origanizations/cryptogen`. Nếu như mà mình chạy `./network.sh ... -ca` (thêm -ca) để tạo thêm CA Server thì script sẽ dùng các file config và file binary `registerEnroll.sh` trong folder `organizations/fabric-ca`. Các MSP Folders và các thông tin khác về crypto sẽ được tạo cho cả 3 organnization (org1, org2 và orderer). Giờ thì hiểu trong đoạn code ở trên lẫn một số đoạn code khác thì file nó được đọc ở đâu rồi đó :D. Vậy thì đã rõ được `cryptogen` và `fabric-ca` làm gì rồi nhé!
- Khi những thông tin cần thiết về crypto được tạo nên thì lúc này `./network.sh` đã có thể startup NET, để làm được thì nó phải dùng file config `test-network/docker/docker-compose-test-net.yaml` để có thể setup và deploy NET lên Docker Container. Ngoài ra thì nó cũng sẽ dùng 2 files còn lại trong folder đó là `docker-compose-ca.yaml` và `docker-compose-couch.yaml` để lần lượt setup và deploy CA Servers và DB cho mỗi peer.
- Khi sử dụng thêm lệnh `createChannel`, thì file binary `createChannel.sh` trong thư mục `test-network/scripts` sẽ được thực thi, nó sẽ dùng file `configtx/configtx.yaml` để tạo ra channel. Sau khi tạo xong thì nó sẽ dùng PEER CLI để thêm 2 peers (`peer0.org1.example.com` và `peer0.org2.example.com`) vào trong channel.

Ok, tới đây thì đã gần rõ được hết từng components trong `test-network` rồi nhé.

## Tổng kết
1. Trong `hyperledger/fabric-samples/test-network` thì là folder dùng để khởi tạo từ A-Z một NET. Bao gồm các organizations là Org1, Org2 và Orderer. Thì mình có thể dùng luôn cái này hoặc là config lại cho gọn hơn để phụ hợp với ứng dụng của mình.
2. Khi sử dụng lệnh `./network.sh up createChannel -ca -s couchdb` thì script sẽ dùng các file configs trong `origanizations/cryptogen` để tạo Certificates và Keys cho Org1 và Org2; sau đó là dùng các file configs và file binary `registerEnroll.sh` trong `organizations/fabric-ca` để tạo các CA Server cũng như là thông tin crypto và MSP Folders; Sau đó là deploy lần lượt CA Servers, DB và NET lên Docker Container dựa theo các file configs trongg `test-network/docker`; Khi mọi thứ đã ok thì tới lúc tạo channel, dựa trên file `configtx/configtx.yaml` và sau khi tạo channel xong thì nó sẽ dùng PEER CLI để thêm lần lượt Org1 và Org2 vào trong channel.

## Tham khảo
<p>[1] <strong>Trust Me Bro</strong></p>
<p>[2] <strong>Write Your First Application</strong>; Hyperledger Document; source: <a href="https://hyperledger-fabric.readthedocs.io/en/release-2.2/write_first_app.html">https://hyperledger-fabric.readthedocs.io/en/release-2.2/write_first_app.html</a></p>
<p>[3] <strong>Application</strong>; Hyperledger Document; source: <a href="https://hyperledger-fabric.readthedocs.io/en/release-2.2/developapps/application.html">https://hyperledger-fabric.readthedocs.io/en/release-2.2/developapps/application.html</a></p>
<p>[4] <strong>Test Network</strong>; Hyperledger Document; source: <a href="https://hyperledger-fabric.readthedocs.io/en/latest/test_network.html">https://hyperledger-fabric.readthedocs.io/en/latest/test_network.html</a></p>
